# Generated by Django 4.0.1 on 2022-01-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='seats',
            new_name='allowedPassengers',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='license',
            new_name='licensePlateNumber',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='specialText',
            new_name='specialInfo',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='vehicle',
            new_name='vehicleType',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='arrival',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='specialText',
            new_name='specialRequests',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='departure',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driverWho',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='isConfirmed',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ride.driver'),
        ),
        migrations.AddField(
            model_name='ride',
            name='partySize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.user'),
        ),
        migrations.CreateModel(
            name='JoinRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partySize', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.user')),
            ],
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, related_name='sharer', to='ride.JoinRide'),
        ),
    ]
