# Generated by Django 4.0.1 on 2022-01-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_rename_seats_driver_allowedpassengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicleTypeRequest',
            field=models.TextField(blank=True, default=''),
        ),
    ]
